name: 🐛Bug Report
description: File a bug report
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the Bug
      placeholder: A clear and concise description of what the bug is.
    validation:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      placeholder: |
        Steps to reproduce the behavior:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validation:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected Behaviour
      placeholder: A clear and concise description of what you expected to happen.
    validation:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      placeholder: If applicable, add screenshots to help explain your problem. Highlight this area and drag and drop any file to attach it.
  - type: textarea
    id: desktop
    attributes:
      label: Desktop (please complete the following information):
      value: |
       - OS [e.g. iOS]: 
       - Browser [e.g. chrome, safari]: 
       - Version [e.g. 22]: 
  - type: textarea
    id: smartphone
    attributes:
      label: Smartphone (please complete the following information):
      value: |
       - Device: [e.g. iPhone6]
       - OS: [e.g. iOS8.1]
       - Browser [e.g. stock browser, safari]
       - Version [e.g. 22]
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      placeholder: Add any other context about the problem here.
    
